#!/usr/bin/env python3
"""Fetch the UI icon set, with the colour slots left open.

WHY THESE ICONS ARE NOT VENDORED AS-DRAWN. Every published IconPark file has a
colour already in it (its own blue). This app has twelve colour schemes, so a
baked-in blue is wrong in eleven of them. IconPark's source modules happen to
parameterise every fill already — `props.colors[0]`, `props.colors[1]`, ... —
so the only thing this script has to do is RESOLVE those to the tokens the app
substitutes at paint time, and record a hash so the result can be audited.

Output: assets/ui_icons/<Name>.svg, each containing `__C0__`..`__C3__`, PLUS
`lib/ui/components/ui_icons.g.dart` with the same templates as Dart constants.

WHY THE SECOND OUTPUT. The icons then need no asset load, so there is no
`await` before the first icon can be drawn and no bootstrap step anyone can
forget. The SVGs stay in the repository as the audit trail — they are NOT
declared in `pubspec.yaml`, so they are not in the shipped bundle.

    python3 tool/fetch_ui_icons.py            # fetch, verify, write
    python3 tool/fetch_ui_icons.py --check    # verify only, write nothing
"""

import hashlib
import json
import os
import re
import sys
import urllib.request

VERSION = '1.4.2'
BASE = f'https://unpkg.com/@icon-park/svg@{VERSION}/es/icons/{{}}.js'
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'assets', 'ui_icons')
MANIFEST = os.path.join(OUT, 'manifest.json')
GENERATED = os.path.join(ROOT, 'lib', 'ui', 'components', 'ui_icons.g.dart')

# Which icon fills which slot in the app. The comment is the SURFACE, because
# that is the thing that must not drift — the glyph behind it can be swapped
# without anything else changing.
ICONS = {
    'Workbench': 'dock, Board tab',
    'AllApplication': 'dock, Workspaces tab',
    'SettingTwo': 'dock, Settings tab',
    'Paperclip': 'terminal navbar, attach',
    'BlocksAndArrows': 'terminal navbar, pane switcher',
    'LayoutFour': 'terminal navbar, split layout',
    'MoreTwo': 'terminal navbar, overflow',
    'Server': 'board navbar, machine entry',
    'Folder': 'terminal menu, browse files',
    'Branch': 'terminal menu, git changes',
    'Aiming': 'terminal menu, move machine focus',
    'Terminal': 'board, open a terminal on a machine',
}

SIZE = 48
STROKE = 4

# How many colour slots each icon actually has, recorded because it is the one
# thing about this set that cannot be fixed by picking better: `Paperclip` uses
# a single slot and will therefore stay flat no matter what palette it is given,
# and the others range from two to four. A dock assembled from these is not
# uniformly colourful, and that is worth knowing before adopting it.
# Regenerate with `python3 -c` against the fetched files if the set changes.


def fetch(name: str) -> str:
    req = urllib.request.Request(BASE.format(name), headers={'User-Agent': 'herdr-pocket'})
    with urllib.request.urlopen(req, timeout=30) as response:
        return response.read().decode('utf-8')


def to_template(name: str) -> str:
    """Resolve IconPark's source module into an SVG with `__Cn__` slots."""
    src = fetch(name)
    match = re.search(r'return\s+(.*?);\s*\}\);\s*$', src, re.S)
    if not match:
        raise SystemExit(f'{name}: no return expression — the package layout changed')
    body = match.group(1).strip()

    # Colours first: `props.colors[1]` must not be eaten by a bare `props.colors`.
    body = re.sub(r'props\.colors\[(\d+)\]', lambda m: f"'__C{m.group(1)}__'", body)
    literals = {
        'size': str(SIZE),
        'strokeWidth': str(STROKE),
        'strokeLinejoin': 'round',
        'strokeLinecap': 'round',
    }
    body = re.sub(r'props\.(\w+)', lambda m: f"'{literals.get(m.group(1), '')}'", body)

    svg = eval(body)  # a chain of string literals and the literals above
    if '__C' not in svg:
        raise SystemExit(f'{name}: no colour slots — this icon cannot be themed')

    # The XML declaration is noise inside a Flutter asset and trips some
    # parsers; the rest is taken verbatim.
    svg = svg.replace('<?xml version="1.0" encoding="UTF-8"?>', '')
    svg = re.sub(r'<svg width="\d+" height="\d+"', '<svg width="48" height="48"', svg, count=1)
    if not svg.endswith('\n'):
        svg += '\n'
    return svg


def write_dart(manifest: dict) -> None:
    """Emit the templates as Dart constants, in the manifest's own order."""
    lines = [
        '// GENERATED by tool/fetch_ui_icons.py — do not edit by hand.',
        '//',
        f'// Source: {manifest["package"]} {manifest["version"]} ({manifest["license"]}).',
        '// Each template carries `__C0__`..`__C3__` where the colours go.',
        '// ignore_for_file: lines_longer_than_80_chars',
        '',
        '/// The UI icon templates, keyed by the base name in `assets/ui_icons/`.',
        'const Map<String, String> uiIconTemplates = {',
    ]
    for name, entry in manifest['files'].items():
        svg = open(os.path.join(OUT, f'{name}.svg'), encoding='utf-8').read().rstrip('\n')
        escaped = svg.replace("'", r"\'")
        lines.append(f"  '{name}': '{escaped}',")
    lines += ['};', '']
    with open(GENERATED, 'w', encoding='utf-8') as handle:
        handle.write('\n'.join(lines))


def main() -> int:
    check_only = '--check' in sys.argv
    os.makedirs(OUT, exist_ok=True)
    previous = {}
    if os.path.exists(MANIFEST):
        previous = json.load(open(MANIFEST, encoding='utf-8')).get('files', {})

    manifest = {'package': '@icon-park/svg', 'version': VERSION, 'license': 'Apache-2.0', 'files': {}}
    failures = []
    for name, surface in ICONS.items():
        try:
            svg = to_template(name)
        except SystemExit as error:
            failures.append(str(error))
            continue
        digest = hashlib.sha256(svg.encode('utf-8')).hexdigest()
        manifest['files'][name] = {'surface': surface, 'sha256': digest}
        if check_only:
            if previous.get(name, {}).get('sha256') != digest:
                failures.append(f'{name}: hash differs from the recorded one')
            continue
        with open(os.path.join(OUT, f'{name}.svg'), 'w', encoding='utf-8') as handle:
            handle.write(svg)
        print(f'{name:18} {surface:34} {digest[:16]}')

    # A file left behind from an earlier set is a file nothing draws but
    # everything ships; the manifest is the list, so make the directory match it.
    if not check_only:
        for stale in os.listdir(OUT):
            if stale.endswith('.svg') and stale[:-4] not in ICONS:
                os.remove(os.path.join(OUT, stale))
                print(f'removed stale {stale}')

    if failures:
        print('\n' + '\n'.join(failures), file=sys.stderr)
        return 1
    if not check_only:
        with open(MANIFEST, 'w', encoding='utf-8') as handle:
            json.dump(manifest, handle, indent=2, ensure_ascii=False)
            handle.write('\n')
        write_dart(manifest)
        print(f'\n{len(ICONS)} icons -> assets/ui_icons/ + ui_icons.g.dart')
    else:
        print(f'{len(ICONS)} icons verified')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
